//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JuJuLocaldbEntities : DbContext
    {
        public JuJuLocaldbEntities()
            : base("name=JuJuLocaldbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Announcement> Announcement { get; set; }
        public virtual DbSet<Chairman> Chairman { get; set; }
        public virtual DbSet<Collector> Collector { get; set; }
        public virtual DbSet<Complaint> Complaint { get; set; }
        public virtual DbSet<Janitor> Janitor { get; set; }
        public virtual DbSet<Meeting> Meeting { get; set; }
        public virtual DbSet<Package> Package { get; set; }
        public virtual DbSet<Resident> Resident { get; set; }
        public virtual DbSet<ReturnOfGoods> ReturnOfGoods { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
